"""Generate records/INDEX.md."""

from __future__ import annotations

from pathlib import Path

from .config import Config
from .loader import load_records


def build_index(config: Config) -> str:
    records = [r.data for r in load_records(config.records_dir) if r.data]
    records.sort(key=lambda r: r["id"])
    by_status: dict[str, int] = {}
    for r in records:
        by_status[r["status"]] = by_status.get(r["status"], 0) + 1

    lines = [
        "# Record index",
        "",
        "Generated by `oml index`; do not edit by hand.",
        "",
        f"{len(records)} records: "
        + ", ".join(f"{n} {s}" for s, n in sorted(by_status.items())) + ".",
        "",
        "| id | title | kind | status | trust |",
        "|----|-------|------|--------|-------|",
    ]
    for r in records:
        rel = _rel_path(config, r["id"])
        lines.append(f"| [`{r['id']}`]({rel}) | {r['title']} | `{r['kind']}` | `{r['status']}` | `{r.get('trust', 'low')}` |")
    lines.append("")
    return "\n".join(lines)


def _rel_path(config: Config, record_id: str) -> str:
    domain, _, rest = record_id.partition(".")
    return f"{domain}/{rest}.json"


def write_index(config: Config) -> Path:
    out = config.records_dir / "INDEX.md"
    out.write_text(build_index(config), encoding="utf-8")
    return out
